# Generated by Django 2.1.5 on 2019-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_auto_20190625_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=25, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='男', max_length=20),
        ),
    ]
