# Generated by Django 2.1.5 on 2019-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_auto_20190627_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
