# Generated by Django 2.1.5 on 2019-07-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aobi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Appliaction')),
                ('hobj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Host')),
            ],
        ),
    ]
