# Generated by Django 2.1.5 on 2019-07-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_appliaction_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobi',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
